version: "1"
services:
  web:
    build: .
    depends_on:
      - postgres
    environment:
      MIX_ENV: dev
      DATABASE_URL: ecto://postgres:postgres@postgres/phoenix_dev
      SECRET_KEY_BASE: beep-beep # Generate with `mix phx.gen.secret` PS: This is just a throwaway key
    ports:
      - '4000:4000'
  postgres:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phoenix_dev
